apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
<<<<<<< HEAD
  username: YWRtaW4=
  passphrase: MWYyZDFlMmU2N2Rm
=======
  username: YQBkAG0AaQBuAA==
  passphrase: YQBkAG0AaQBuAA==
>>>>>>> abb108e03dd0ddf0b43d7ea4b2f5b307452ac88e
